<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="DukaNasi helps Tanzanian businesses manage sales, expenses, stock, customers and loans in one simple platform.">
    <title>DukaNasi — Biashara yako, kwa urahisi</title>
    <style>
        :root{--ink:#10261f;--green:#0b6b4b;--mint:#dff4e8;--gold:#ffb31a;--cream:#fbf8f0;--muted:#60716b;--line:#dfe7e2;--white:#fff}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);background:var(--cream);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;line-height:1.5}a{text-decoration:none;color:inherit}.wrap{width:min(1180px,calc(100% - 40px));margin:auto}
        .nav{height:80px;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:11px;font-size:25px;font-weight:850;letter-spacing:-1px}.brand-mark{width:37px;height:37px;display:grid;place-items:center;background:var(--green);border-radius:10px;color:#fff;box-shadow:inset 0 -7px 0 rgba(0,0,0,.1)}.brand span{color:#ef9b00}.links{display:flex;gap:34px;font-size:14px;font-weight:650}.actions{display:flex;align-items:center;gap:13px}.btn{display:inline-flex;align-items:center;justify-content:center;gap:10px;min-height:47px;padding:0 22px;border:1px solid transparent;border-radius:11px;font-weight:750;font-size:14px;transition:.2s}.btn:hover{transform:translateY(-2px)}.btn-gold{background:var(--gold);color:#15241e;box-shadow:0 10px 25px rgba(255,179,26,.24)}.btn-line{border-color:#bfcac4;background:rgba(255,255,255,.5)}.menu{display:none;background:none;border:0;font-size:25px}
        .hero{position:relative;overflow:hidden;padding:70px 0 92px;background:radial-gradient(circle at 83% 21%,#ffe8ab 0,rgba(255,232,171,.48) 16%,transparent 38%)}.hero-grid{display:grid;grid-template-columns:.9fr 1.1fr;gap:58px;align-items:center}.eyebrow{display:inline-flex;align-items:center;gap:8px;padding:8px 12px;border-radius:999px;background:var(--mint);color:var(--green);font-size:12px;font-weight:800;letter-spacing:.06em;text-transform:uppercase}.dot{width:7px;height:7px;border-radius:50%;background:var(--green)}h1{font-size:clamp(46px,5vw,72px);line-height:.99;letter-spacing:-4px;margin:24px 0 24px;max-width:650px}h1 em{font-style:normal;color:var(--green)}.lead{font-size:19px;color:var(--muted);max-width:570px;margin:0 0 30px}.hero-actions{display:flex;gap:12px;flex-wrap:wrap}.fine{display:flex;gap:20px;margin-top:20px;color:#687871;font-size:12px}.fine span:before{content:'✓';color:var(--green);font-weight:900;margin-right:6px}
        .app{position:relative;background:#fff;border:1px solid rgba(16,38,31,.1);border-radius:22px;padding:13px;box-shadow:0 35px 80px rgba(18,58,45,.16);transform:rotate(1deg)}.app-inner{overflow:hidden;border:1px solid var(--line);border-radius:14px;background:#f8faf9}.app-top{height:50px;padding:0 18px;display:flex;align-items:center;justify-content:space-between;background:#fff;border-bottom:1px solid var(--line);font-size:12px}.app-main{display:grid;grid-template-columns:112px 1fr}.side{padding:16px 9px;background:#f2f7f4}.side div{padding:9px 10px;margin-bottom:4px;border-radius:7px;font-size:10px}.side .active{background:#dcefe5;color:var(--green);font-weight:750}.dash{padding:18px}.dash-head{display:flex;align-items:start;justify-content:space-between}.dash h3{margin:0;font-size:17px}.dash small{color:var(--muted)}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:14px 0}.stat{background:#fff;border:1px solid var(--line);border-radius:10px;padding:11px}.stat small{font-size:9px}.stat strong{display:block;font-size:14px;margin-top:4px}.up{color:#0b9b58;font-size:9px;font-weight:800}.chart{height:150px;background:#fff;border:1px solid var(--line);border-radius:10px;padding:12px}.chart svg{width:100%;height:105px}.chart-title{display:flex;justify-content:space-between;font-size:10px;font-weight:750}.float-card{position:absolute;border-radius:13px;background:#fff;padding:13px 16px;box-shadow:0 14px 35px rgba(12,52,39,.17);font-size:10px}.float-card strong{display:block;font-size:15px;margin-top:3px}.fc1{left:-34px;bottom:46px;border-left:4px solid var(--green)}.fc2{right:-26px;top:110px;border-left:4px solid var(--gold)}
        .proof{background:#fff;border-block:1px solid var(--line)}.proof-row{min-height:92px;display:flex;align-items:center;justify-content:space-between;gap:25px}.proof-row p{font-weight:750}.sectors{display:flex;gap:28px;color:var(--muted);font-size:13px}.sectors span{white-space:nowrap}
        .section{padding:100px 0}.section-head{display:flex;align-items:end;justify-content:space-between;gap:30px;margin-bottom:38px}.kicker{color:var(--green);font-weight:850;font-size:12px;letter-spacing:.13em}.section h2{font-size:clamp(35px,4vw,52px);line-height:1.05;letter-spacing:-2.3px;margin:10px 0 0}.section-head p{color:var(--muted);max-width:390px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.card{background:#fff;border:1px solid var(--line);border-radius:18px;padding:27px;transition:.2s}.card:hover{transform:translateY(-5px);box-shadow:0 18px 40px rgba(16,38,31,.08)}.icon{width:48px;height:48px;border-radius:13px;background:var(--mint);display:grid;place-items:center;font-size:22px}.card:nth-child(2n) .icon{background:#fff0c8}.card h3{font-size:19px;margin:20px 0 8px}.card p{color:var(--muted);font-size:14px;margin:0}.dark{background:var(--ink);color:#fff;border-radius:28px;padding:62px;display:grid;grid-template-columns:1fr 1fr;gap:70px;align-items:center}.dark h2{margin:10px 0 18px}.dark p{color:#b8c8c2}.numbers{display:grid;grid-template-columns:1fr 1fr;gap:12px}.number{background:rgba(255,255,255,.075);border:1px solid rgba(255,255,255,.11);border-radius:15px;padding:22px}.number strong{display:block;color:var(--gold);font-size:31px}.number span{font-size:12px;color:#c6d2cd}
        footer{background:#071b15;color:#cfdbd6;padding:30px 0}.footer-row{display:flex;justify-content:space-between;align-items:center;font-size:12px}
        @media(max-width:900px){.links{display:none}.menu{display:block}.actions .signin{display:none}.hero{padding-top:35px}.hero-grid{grid-template-columns:1fr}.app{margin:20px 20px 0}.proof-row,.section-head{align-items:flex-start;flex-direction:column}.sectors{overflow:auto;width:100%;padding-bottom:10px}.cards{grid-template-columns:1fr 1fr}.dark{grid-template-columns:1fr;padding:38px;gap:35px}}
        @media(max-width:600px){.wrap{width:min(100% - 26px,1180px)}.nav{height:68px}.actions .btn{display:none}h1{letter-spacing:-2.6px}.fine{flex-direction:column;gap:7px}.app{margin:10px 0 0}.app-main{grid-template-columns:1fr}.side{display:none}.fc1{left:-8px;bottom:30px}.fc2{right:-8px;top:96px}.proof-row{padding:22px 0}.cards{grid-template-columns:1fr}.section{padding:70px 0}.dark{border-radius:20px;padding:28px}.numbers{grid-template-columns:1fr 1fr}.footer-row{align-items:flex-start;flex-direction:column;gap:14px}}
    </style>
</head>
<body>
<header class="wrap nav">
    <a class="brand" href="#"><b class="brand-mark">D</b>Duka<span>Nasi</span></a>
    <nav class="links"><a href="#features">Features</a><a href="#solutions">Solutions</a><a href="#pricing">Pricing</a><a href="#about">About</a></nav>
    <div class="actions">
        @if (Route::has('login'))<a class="signin" href="{{ route('login') }}">Sign in</a>@endif
        @if (Route::has('register'))<a class="btn btn-gold" href="{{ route('register') }}">Start free →</a>@endif
        <button class="menu" aria-label="Open menu">☰</button>
    </div>
</header>
<main>
    <section class="hero"><div class="wrap hero-grid">
        <div><div class="eyebrow"><i class="dot"></i> Built for Tanzanian businesses</div><h1>Biashara yako, <em>under control.</em></h1><p class="lead">Track sales, expenses, inventory, customers and loans from one simple platform—and make every business decision with confidence.</p><div class="hero-actions">@if (Route::has('register'))<a class="btn btn-gold" href="{{ route('register') }}">Start free for 14 days →</a>@endif<a class="btn btn-line" href="#features">Explore DukaNasi</a></div><div class="fine"><span>No card required</span><span>Set up in minutes</span><span>Local support</span></div></div>
        <div class="app"><div class="app-inner"><div class="app-top"><b>▣ DukaNasi</b><span>Kariakoo Traders&nbsp;&nbsp; ●</span></div><div class="app-main"><aside class="side"><div class="active">⌂ &nbsp; Overview</div><div>▥ &nbsp; Sales</div><div>▤ &nbsp; Expenses</div><div>◇ &nbsp; Inventory</div><div>◎ &nbsp; Loans</div><div>▦ &nbsp; Reports</div></aside><div class="dash"><div class="dash-head"><div><h3>Good morning, Amina</h3><small>Here is your business today.</small></div><small>September 2026</small></div><div class="stats"><div class="stat"><small>Sales today</small><strong>TSh 485,000</strong><span class="up">↗ 12%</span></div><div class="stat"><small>Expenses</small><strong>TSh 120,000</strong><span class="up">On track</span></div><div class="stat"><small>Net profit</small><strong>TSh 365,000</strong><span class="up">↗ 18%</span></div></div><div class="chart"><div class="chart-title"><span>Weekly performance</span><span>This week⌄</span></div><svg viewBox="0 0 440 110" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#36b37e" stop-opacity=".28"/><stop offset="1" stop-color="#36b37e" stop-opacity="0"/></linearGradient></defs><path d="M0 86 C45 78,55 52,100 62 S160 80,205 48 S270 70,320 43 S390 50,440 19 L440 110 L0 110Z" fill="url(#g)"/><path d="M0 86 C45 78,55 52,100 62 S160 80,205 48 S270 70,320 43 S390 50,440 19" fill="none" stroke="#149261" stroke-width="3"/></svg></div></div></div></div><div class="float-card fc1">Today’s revenue<strong>TSh 485,000</strong></div><div class="float-card fc2">Low stock<strong>5 products</strong></div></div>
    </div></section>
    <section class="proof"><div class="wrap proof-row"><p>Made for businesses that move Tanzania</p><div class="sectors"><span>◉ Retail & kiosks</span><span>◉ Restaurants</span><span>◉ Wholesale</span><span>◉ Services</span></div></div></section>
    <section class="section" id="features"><div class="wrap"><div class="section-head"><div><span class="kicker">ONE SIMPLE PLATFORM</span><h2>Everything you need<br>to run your business.</h2></div><p>Less paperwork, fewer surprises and a clear view of what is happening every day.</p></div><div class="cards"><article class="card"><div class="icon">↗</div><h3>Sales made simple</h3><p>Record every sale quickly and understand which products drive your revenue.</p></article><article class="card"><div class="icon">▣</div><h3>Smart inventory</h3><p>Know what is in stock and receive alerts before your best sellers run out.</p></article><article class="card"><div class="icon">◫</div><h3>Clear expenses</h3><p>Track where money goes and protect your profit with accurate daily records.</p></article><article class="card"><div class="icon">◎</div><h3>Loans & credit</h3><p>Manage money owed, repayments and customer credit without losing track.</p></article><article class="card"><div class="icon">▥</div><h3>Useful reports</h3><p>Turn your daily records into simple insights you can act on immediately.</p></article><article class="card"><div class="icon">♙</div><h3>Customer records</h3><p>Keep customer details and purchase history together to build loyalty.</p></article></div></div></section>
    <section class="section" id="solutions"><div class="wrap dark"><div><span class="kicker" style="color:#8ce0b7">YOUR NUMBERS, MADE CLEAR</span><h2>Make smarter moves with real business data.</h2><p>DukaNasi turns daily activity into a clear picture of performance—so you know what to improve and where to grow.</p><br>@if (Route::has('register'))<a class="btn btn-gold" href="{{ route('register') }}">Grow with DukaNasi →</a>@endif</div><div class="numbers"><div class="number"><strong>1</strong><span>place for your whole business</span></div><div class="number"><strong>24/7</strong><span>access to your records</span></div><div class="number"><strong>100%</strong><span>clear business visibility</span></div><div class="number"><strong>TSh</strong><span>built around local business</span></div></div></div></section>
</main>
<footer><div class="wrap footer-row"><a class="brand" style="font-size:19px" href="#"><b class="brand-mark" style="width:30px;height:30px">D</b>Duka<span>Nasi</span></a><span>© {{ date('Y') }} DukaNasi. Biashara bora, kila siku.</span></div></footer>
</body>
</html>
